const ownerEmailTemplate = ({ fullName, email, contactNumber, companyName, message }) => `
  <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
    <div style="max-width: 600px; background: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.2);">
      <div style="text-align: center; padding-bottom: 20px; border-bottom: 2px solid #007bff;">
        <h2 style="color: #333;">📩 New Contact Form Submission</h2>
      </div>
      <p><strong>Name:</strong> ${fullName}</p>
      <p><strong>Email:</strong> <a href="mailto:${email}" style="color: #007bff;">${email}</a></p>
      <p><strong>Contact Number:</strong> ${contactNumber || 'Not provided'}</p>
      <p><strong>Message:</strong></p>
      <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #007bff;">
        <p style="margin: 0;">${message}</p>
      </div>
      <hr>
      <p style="text-align: center; font-size: 14px; color: #777;">Generated by Your App</p>
    </div>
  </div>
`;

export default ownerEmailTemplate;