const userEmailTemplate = ({ fullName, message }) => `
  <div style="font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px;">
    <div style="max-width: 600px; background: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.2);">
      <div style="text-align: center; padding-bottom: 20px; border-bottom: 2px solid #28a745;">
        <h2 style="color: #007bff;">✨ Thank You for Contacting Us!</h2>
      </div>
      <p>Dear <strong>${fullName}</strong>,</p>
      <p>Thank you for reaching out! We'll respond soon.</p>
      <p><strong>Your Message:</strong></p>
      <div style="background: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #28a745;">
        <p style="margin: 0;">${message}</p>
      </div>
      <p>Contact us at <a href="mailto:support@yourapp.com" style="color: #007bff;">support@yourapp.com</a> for urgent queries.</p>
      <hr>
      <p style="text-align: center; font-size: 14px; color: #777;">Generated by Your App</p>
    </div>
  </div>
`;

export default userEmailTemplate;